@startuml

abstract class Element {
  + ID: int
  + get_ID(): int
  + iterate(): void
}

abstract class NonPipe {
  + c_characteristic: double
  + b_characteristic: double
  + set_c_characteristic(val): void
  + set_b_characteristic(val): void

}

abstract class Pipe {
  - H: vector<double>
  - Q: vector<double>
}

class Reservoir {
  + HR: int
}

class Valve {
  - State: Open | Closed
  + set_state(state: Open | Closed): void
  + is_open(): bool
}

class Pump {
}

class AlgebraicPipe {
}

class NormalPipe {
}

class Plant {
  - container: PlantContainer
  - state: State
  + Plant(file_path: string)
  + get_state(): State
  + step(): void
  + run_steps(in: int): void
  + stop(): void
  + pause(): void
  + resume(): void
}


class PlantContainer {
  - elements: vector<Element>
  + add_element(Element): void
  + remove_element(ElementID): boolean
  + get_element_by_ID(id): Element
}

class PlantConfiguration {
  + elements: vector<Element>
  + time_step: double
}

class ConfigurationService << (S,#FF7700) Singleton >> {
  + read_plant_from_file(path): PlantConfiguration
  + save_plant_to_file(path, plant): Result
}



' Relations 
ConfigurationService -- PlantConfiguration 

Element <|-- NonPipe
Element <|-- Pipe

NonPipe <|-- Reservoir
NonPipe <|-- Valve
NonPipe <|-- Pump

Pipe <|-- AlgebraicPipe
Pipe <|-- NormalPipe

PlantContainer o-- Element

Plant -- PlantContainer
Plant -- ConfigurationService

@enduml
